[build]
  # Directory to publish (contains the built site)
  publish = "."
  
  # Build command (not needed for static site)
  command = ""

[build.environment]
  # Node.js version (if needed for build tools)
  NODE_VERSION = "18"

# SPA fallback for unmatched routes (existing files are served normally)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'; connect-src 'self' https://www.islamibankbd.com;"

# Cache static assets - but allow cache busting
[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "public, max-age=300"
    Content-Type = "text/css"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Font optimization
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Performance optimization - disable processing that might break CSS
[build.processing]
  skip_processing = true
